In [12]:
import pandas as pd
import numpy as np

np.random.seed(0)

df = pd.DataFrame({'person_id': [3616969], 'gender_person': ['Female'], 'date_of_birth_person': ['1982-06-16 00:00:00+00:00'], 'race_person': ['White'], 
                  'ethnicity_person': ['Hispanic or Latino'], 'sex_at_birth_person': ['Female'], 'observation_datetime_zip': ['2020-02-14 18:47:27+00:00'], 
                   'zip_code_zip': ['441**'], 'assisted_income_zip': [38.279736], 'high_school_education_zip': [70.896923], 'median_income_zip': [39407.415829], 
                   'no_health_insurance_zip': [11.049983], 'poverty_zip': [29.653439], 'vacant_housing_zip': [5.505385], 'deprivation_index_zip': [0.485979], 
                   'american_community_survey_year_zip': [2017], 'condition_start_date': ['2021-08-11'], 'birth_class': ['Term'], 'gestational_age_at_birth': [28.0], 
                   'birth_order': [1], 'birth_class_binary': [0] })

In [13]:
for z in range(20):    
    y = df.iloc[[-1], :]
    y.index = y.index + 1
    y.person_id = y.person_id + 1
    y.age_at_birth = np.random.randint(15,40)
    y.gestational_age_at_birth = y.age_at_birth - np.random.uniform(0.45,0.65)

    
    
   
    df = pd.concat([df,y]).sort_index()

    if z % 4 == 0:
        df.at[z, 'race_person'] = 'Black'
    elif z % 3 == 0:
        df.at[z, 'race_person'] = 'Asian'
    elif z % 2 == 0:
        df.at[z, 'ethnicity_person'] = 'Not Hispanic or Latino'
    if z % 5 == 0:
        df.at[z, 'zip_code_zip'] = '701**'
        df.at[z, 'assisted_income_zip'] = '25.2'
        df.at[z, 'median_income_zip'] = '25000.1'
        df.at[z, 'high_school_education_zip'] = '54'
        df.at[z, 'no_health_insurance_zip'] = '14.2'
        df.at[z, 'poverty_zip'] = '29.61'
        df.at[z, 'vacant_housing_zip'] = '7.78'
        df.at[z, 'deprivation_index_zip'] = '0.56'
    if z % 10 == 0:
        df.at[z, 'birth_class'] = 'Preterm' #approximating frequency in dataset, one can change this to accord with p = 0.14 in diceroll or change p accordingly.
        #df.at[z, 'birth_order'] replace as appropriate
        #df.at[z, 'birth_class_binary'] replace as appropriate
    
    #right now last record is duplicate of first in some ways?

/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [89]:
#df.iloc[lambda x: x.index % 4 == 0].race_person = 'Black'
#df.at[4, 'race_person'] = 'Black'

In [14]:
df

,person_id,gender_person,date_of_birth_person,race_person,ethnicity_person,sex_at_birth_person,observation_datetime_zip,zip_code_zip,assisted_income_zip,high_school_education_zip,...,no_health_insurance_zip,poverty_zip,vacant_housing_zip,deprivation_index_zip,american_community_survey_year_zip,condition_start_date,birth_class,gestational_age_at_birth,birth_order,birth_class_binary
0,3616969,Female,1982-06-16 00:00:00+00:00,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Preterm,28.000000,1,0
1,3616970,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,26.431431,1,0
2,3616971,Female,1982-06-16 00:00:00+00:00,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,14.429447,1,0
3,3616972,Female,1982-06-16 00:00:00+00:00,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,17.380550,1,0
4,3616973,Female,1982-06-16 00:00:00+00:00,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.420821,1,0
5,3616974,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Term,18.490493,1,0
6,3616975,Female,1982-06-16 00:00:00+00:00,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,38.357267,1,0
7,3616976,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,15.391655,1,0
8,3616977,Female,1982-06-16 00:00:00+00:00,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,37.454005,1,0
9,3616978,Female,1982-06-16 00:00:00+00:00,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,31.364881,1,0
10,3616979,Female,1982-06-16 00:00:00+00:00,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Preterm,27.482521,1,0
11,3616980,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,34.545956,1,0
12,3616981,Female,1982-06-16 00:00:00+00:00,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.358569,1,0
13,3616982,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,29.375998,1,0
14,3616983,Female,1982-06-16 00:00:00+00:00,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,32.455278,1,0
15,3616984,Female,1982-06-16 00:00:00+00:00,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Term,31.457704,1,0
16,3616985,Female,1982-06-16 00:00:00+00:00,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.414224,1,0
17,3616986,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,21.422016,1,0
18,3616987,Female,1982-06-16 00:00:00+00:00,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,23.442525,1,0
19,3616988,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,14.445630,1,0
20,3616989,Female,1982-06-16 00:00:00+00:00,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,34.455280,1,0

In [15]:
def random_dates(start, end, n, unit='D', seed=None):
    if not seed:  
        np.random.seed(0)

    ndays = (end - start).days + 1
    return start + pd.to_timedelta(
        np.random.randint(0, ndays, n), unit=unit)

start = pd.to_datetime('1995-01-01')
end = pd.to_datetime('2002-01-01')
rdv = random_dates(start, end, 21)
rdv = rdv.to_frame(index=False, name='date_of_birth') #can replace observation date/time as needed too, as per next cell

In [16]:
df["date_of_birth_person"] = rdv["date_of_birth"]

In [17]:
df

,person_id,gender_person,date_of_birth_person,race_person,ethnicity_person,sex_at_birth_person,observation_datetime_zip,zip_code_zip,assisted_income_zip,high_school_education_zip,...,no_health_insurance_zip,poverty_zip,vacant_housing_zip,deprivation_index_zip,american_community_survey_year_zip,condition_start_date,birth_class,gestational_age_at_birth,birth_order,birth_class_binary
0,3616969,Female,1999-07-12,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Preterm,28.000000,1,0
1,3616970,Female,1997-04-15,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,26.431431,1,0
2,3616971,Female,1997-02-02,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,14.429447,1,0
3,3616972,Female,1999-09-28,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,17.380550,1,0
4,3616973,Female,1997-10-30,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.420821,1,0
5,3616974,Female,1995-10-05,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Term,18.490493,1,0
6,3616975,Female,1999-11-14,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,38.357267,1,0
7,3616976,Female,2000-01-03,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,15.391655,1,0
8,3616977,Female,2001-06-20,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,37.454005,1,0
9,3616978,Female,1996-12-06,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,31.364881,1,0
10,3616979,Female,2000-11-05,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Preterm,27.482521,1,0
11,3616980,Female,2001-01-31,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,34.545956,1,0
12,3616981,Female,1999-08-29,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.358569,1,0
13,3616982,Female,1996-06-21,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,29.375998,1,0
14,3616983,Female,2000-10-21,White,Not Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,32.455278,1,0
15,3616984,Female,2000-04-24,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,701**,25.200000,54.000000,...,14.200000,29.610000,7.780000,0.560000,2017,2021-08-11,Term,31.457704,1,0
16,3616985,Female,2000-12-03,Black,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,33.414224,1,0
17,3616986,Female,1997-09-03,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,21.422016,1,0
18,3616987,Female,1997-01-25,Asian,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,23.442525,1,0
19,3616988,Female,2000-08-08,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,14.445630,1,0
20,3616989,Female,2000-02-15,White,Hispanic or Latino,Female,2020-02-14 18:47:27+00:00,441**,38.279736,70.896923,...,11.049983,29.653439,5.505385,0.485979,2017,2021-08-11,Term,34.455280,1,0